"""Candidate feedback domain entity."""
from dataclasses import dataclass, field
from datetime import datetime
from uuid import UUID

from app.domain.feedback.recommendation import RecommendationCategory


@dataclass
class CandidateFeedback:
    id: UUID
    resume_id: UUID
    job_id: UUID
    # Derived arithmetically from the match score, never generated by an LLM.
    recommendation: RecommendationCategory
    threshold_rationale: str
    summary: str | None = None
    strengths: list[str] = field(default_factory=list)
    weaknesses: list[str] = field(default_factory=list)
    # Restricted to job-relevant, evidence-based observations — never
    # speculation about the person. See the agent's prompt constraints.
    risk_factors: list[str] = field(default_factory=list)
    # Candidate-facing and constructive: these could plausibly be shared
    # with a rejected applicant.
    improvement_suggestions: list[str] = field(default_factory=list)
    # True when the LLM narrative failed but the deterministic
    # recommendation was still produced.
    narrative_generation_failed: bool = False
    created_at: datetime | None = None
