import { useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import { register } from "../api/endpoints";
import { Button, ErrorBanner, Field, inputClass, Spinner } from "../components/ui";

export function LoginPage() {
  const { signIn } = useAuth();
  const navigate = useNavigate();

  const [mode, setMode] = useState<"signin" | "register">("signin");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [fullName, setFullName] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    setError(null);
    setBusy(true);
    try {
      if (mode === "register") {
        await register(email, password, fullName);
      }
      await signIn(email, password);
      navigate("/jobs");
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Sign in failed");
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="min-h-screen grid lg:grid-cols-[1.1fr_1fr]">
      {/* Left panel states what the product actually does, in its own terms.
          The claim it makes — scores decompose — is the thing that
          distinguishes it, so that's the copy rather than a tagline. */}
      <div className="hidden lg:flex flex-col justify-between bg-ink text-white p-12">
        <div className="flex items-baseline gap-2">
          <span className="font-semibold tracking-tight">Screening</span>
          <span className="eyebrow text-signal">advisory</span>
        </div>

        <div className="max-w-md">
          <h1 className="text-3xl font-semibold leading-snug tracking-tight">
            Every score shows its arithmetic.
          </h1>
          <p className="mt-4 text-white/70 leading-relaxed">
            Candidate matches are computed from skills, experience, and education
            against the requirements you set — not generated by a model. Each score
            breaks down into the components that produced it, so you can check the
            reasoning rather than trust the number.
          </p>

          {/* A worked example of the signature element, so the promise above
              is demonstrated rather than asserted. */}
          <div className="mt-8 border border-white/15 rounded-card p-4">
            <div className="flex items-baseline justify-between mb-2.5">
              <span className="eyebrow text-white/50">Example</span>
              <span className="numeric text-lg">0.78</span>
            </div>
            <div className="h-2.5 rounded-full bg-white/10 overflow-hidden flex">
              <div style={{ width: "48%", background: "var(--signal)" }} />
              <div style={{ width: "20%", background: "#6f92b8" }} />
              <div style={{ width: "10%", background: "#7a8fa6" }} />
            </div>
            <div className="mt-2.5 flex gap-4 text-xs text-white/50">
              <span>skills .48</span>
              <span>experience .20</span>
              <span>education .10</span>
            </div>
          </div>
        </div>

        <p className="text-xs text-white/40 max-w-md leading-relaxed">
          This tool is a screening aid. It does not make hiring decisions, and its
          output should be reviewed alongside the full application.
        </p>
      </div>

      <div className="flex items-center justify-center p-6 bg-surface">
        <form onSubmit={submit} className="w-full max-w-sm space-y-5">
          {/* On mobile the left panel is hidden, which would otherwise leave
              a bare form with no product identity or context at all. */}
          <div className="lg:hidden pb-2">
            <div className="flex items-baseline gap-2">
              <span className="font-semibold text-ink tracking-tight">Screening</span>
              <span className="eyebrow text-signal">advisory</span>
            </div>
            <p className="text-sm text-ink-soft mt-1.5 leading-relaxed">
              Candidate matches computed from skills, experience, and education — with the
              arithmetic shown, not hidden.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-ink">
              {mode === "signin" ? "Sign in" : "Create an account"}
            </h2>
            <p className="text-sm text-ink-soft mt-1">
              {mode === "signin"
                ? "Use your recruiter credentials."
                : "The first account created becomes the administrator."}
            </p>
          </div>

          {error && <ErrorBanner message={error} />}

          {mode === "register" && (
            <Field label="Full name">
              <input className={inputClass} value={fullName} required
                onChange={(e) => setFullName(e.target.value)} autoComplete="name" />
            </Field>
          )}

          <Field label="Email">
            <input className={inputClass} type="email" value={email} required
              onChange={(e) => setEmail(e.target.value)} autoComplete="email" />
          </Field>

          <Field label="Password" hint={mode === "register" ? "At least 8 characters." : undefined}>
            <input className={inputClass} type="password" value={password} required minLength={8}
              onChange={(e) => setPassword(e.target.value)}
              autoComplete={mode === "signin" ? "current-password" : "new-password"} />
          </Field>

          <Button type="submit" variant="primary" disabled={busy} className="w-full justify-center">
            {busy ? <Spinner /> : mode === "signin" ? "Sign in" : "Create account"}
          </Button>

          <button type="button"
            onClick={() => { setMode(mode === "signin" ? "register" : "signin"); setError(null); }}
            className="text-sm text-ink-soft hover:text-ink w-full text-center">
            {mode === "signin" ? "Create an account" : "Sign in instead"}
          </button>
        </form>
      </div>
    </div>
  );
}
