"""
Hiring recommendation derivation — deterministic and threshold-based.

WHY THIS ISN'T AN LLM DECISION
------------------------------
Every prior agent produced analysis. This one produces a recommendation
about whether to hire a person, which is a different kind of output: if a
recruiter treats "Do Not Recommend" as authoritative, someone doesn't get
a job because of it.

So the recommendation CATEGORY is derived arithmetically from the Phase 9
match score, not generated by an LLM. That gives three properties that
matter here more than anywhere else in the system:

  - Reproducible: the same candidate always gets the same recommendation.
  - Auditable: "why not recommended?" has an arithmetic answer citing a
    specific threshold, not a narrative that could have gone either way.
  - Consistent: two candidates with identical scores get identical
    recommendations, which is a basic fairness property.

The LLM writes the narrative ABOUT this recommendation. It cannot change it.

THRESHOLDS
----------
These are defensible defaults, not empirically validated cutoffs, and
they're exposed as named constants so they can be tuned. Any organization
using this seriously should calibrate them against their own hiring bar.
"""
from dataclasses import dataclass
from enum import Enum

STRONG_RECOMMEND_THRESHOLD = 0.80
RECOMMEND_THRESHOLD = 0.65
CONSIDER_THRESHOLD = 0.45


class RecommendationCategory(str, Enum):
    STRONG_RECOMMEND = "strong_recommend"
    RECOMMEND = "recommend"
    CONSIDER = "consider"
    NOT_RECOMMENDED = "not_recommended"


# Non-negotiable framing attached to every piece of feedback this system
# produces. Kept as a constant (not prompt text) so it cannot be altered
# or omitted by an LLM, and surfaced as a required response field so any
# consuming UI has to handle it rather than skipping a footnote.
ADVISORY_NOTICE = (
    "This is an automated screening aid, not a hiring decision. It is based solely on "
    "information extracted from the submitted resume and should be reviewed by a human "
    "recruiter alongside the full application. Do not use it as the sole basis for "
    "rejecting or advancing a candidate."
)


@dataclass(frozen=True)
class Recommendation:
    category: RecommendationCategory
    # The arithmetic justification — cites the actual score and threshold,
    # so the decision is traceable to numbers rather than to prose.
    threshold_rationale: str


def derive_recommendation(
    similarity_score: float, missing_required_skills: list[str]
) -> Recommendation:
    """Map a match score to a hiring recommendation category.

    Pure function: no LLM, no randomness, no I/O. Identical inputs always
    produce an identical recommendation.

    Missing required skills gate the top category specifically: a candidate
    scoring well overall while lacking a stated hard requirement shouldn't
    be labelled a strong match, since the requirement was stated as
    mandatory by the recruiter.
    """
    score_text = f"{similarity_score:.2f}"

    if similarity_score >= STRONG_RECOMMEND_THRESHOLD and not missing_required_skills:
        return Recommendation(
            category=RecommendationCategory.STRONG_RECOMMEND,
            threshold_rationale=(
                f"Match score {score_text} meets the strong-recommend threshold of "
                f"{STRONG_RECOMMEND_THRESHOLD:.2f}, and no required skills are missing."
            ),
        )

    if similarity_score >= RECOMMEND_THRESHOLD:
        rationale = (
            f"Match score {score_text} meets the recommend threshold of "
            f"{RECOMMEND_THRESHOLD:.2f}."
        )
        if similarity_score >= STRONG_RECOMMEND_THRESHOLD and missing_required_skills:
            rationale = (
                f"Match score {score_text} would meet the strong-recommend threshold, but "
                f"{len(missing_required_skills)} required skill(s) are missing "
                f"({', '.join(missing_required_skills)}), so the recommendation is capped here."
            )
        return Recommendation(category=RecommendationCategory.RECOMMEND, threshold_rationale=rationale)

    if similarity_score >= CONSIDER_THRESHOLD:
        return Recommendation(
            category=RecommendationCategory.CONSIDER,
            threshold_rationale=(
                f"Match score {score_text} falls between the consider threshold of "
                f"{CONSIDER_THRESHOLD:.2f} and the recommend threshold of "
                f"{RECOMMEND_THRESHOLD:.2f}."
            ),
        )

    return Recommendation(
        category=RecommendationCategory.NOT_RECOMMENDED,
        threshold_rationale=(
            f"Match score {score_text} falls below the consider threshold of "
            f"{CONSIDER_THRESHOLD:.2f}. Note this reflects resume-to-requirements fit only."
        ),
    )
